/**
 * Object storage abstraction (TD-16). Two physically separate buckets:
 * - public: product/category images, addressable by URL;
 * - private: payment proofs — no URL method exists, so a private object can only
 *   be streamed through an authorized route (FD-51).
 */
export interface StoredObjectInfo {
  key: string;
  contentType: string;
  size: number;
}

export interface StoredObject extends StoredObjectInfo {
  body: Uint8Array;
}

interface Bucket {
  put(key: string, body: Uint8Array, contentType: string): Promise<StoredObjectInfo>;
  get(key: string): Promise<StoredObject | null>;
  delete(key: string): Promise<void>;
  exists(key: string): Promise<boolean>;
}

export interface PublicBucket extends Bucket {
  readonly visibility: "public";
  publicUrl(key: string): string;
}

export interface PrivateBucket extends Bucket {
  readonly visibility: "private";
}

export interface ObjectStorage {
  public: PublicBucket;
  private: PrivateBucket;
}

export class StorageKeyError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "StorageKeyError";
  }
}

const KEY_RE = /^[a-z0-9][a-z0-9_-]*(\/[a-z0-9][a-z0-9_-]*)*\.[a-z0-9]{1,8}$/;

/**
 * Keys are generated by the server, never taken from user input: lowercase
 * segments, one extension, no "..", no leading slash, bounded length.
 */
export function assertValidStorageKey(key: string): void {
  if (key.length === 0 || key.length > 256 || !KEY_RE.test(key)) {
    throw new StorageKeyError(`Invalid storage key: ${JSON.stringify(key)}`);
  }
}
