/**
 * Applies pending SQL migrations from ./drizzle. Run with: npm run db:migrate
 * Forward-only; migrations are reviewed SQL files generated by drizzle-kit and
 * checked by `npm run db:check-migrations`. Run it as a separate deploy step
 * before the new app version receives traffic (plan §36.1).
 *
 * A PostgreSQL advisory lock serializes concurrent runs (e.g. two deploys starting
 * at once); drizzle applies each migration file inside a transaction.
 */
import { drizzle } from "drizzle-orm/postgres-js";
import { migrate } from "drizzle-orm/postgres-js/migrator";
import postgres from "postgres";

const MIGRATION_LOCK_ID = 718_202_601; // arbitrary, constant for this app

async function main() {
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL is required");
  // A direct (session) connection is required for the advisory lock — not a transaction-mode pooler.
  const client = postgres(url, { max: 1, onnotice: () => {} });
  try {
    await client`SELECT pg_advisory_lock(${MIGRATION_LOCK_ID})`;
    try {
      await migrate(drizzle(client), { migrationsFolder: "./drizzle" });
      console.log("Migrations applied.");
    } finally {
      await client`SELECT pg_advisory_unlock(${MIGRATION_LOCK_ID})`;
    }
  } finally {
    await client.end({ timeout: 5 });
  }
}

main().catch((error: unknown) => {
  // Never print the connection string.
  console.error(error instanceof Error ? error.message : "Migration failed");
  process.exit(1);
});
